use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'AWBaseSDK_Example' do
  pod 'AWBaseSDK', :path => '../'
  

  
  target 'AWBaseSDK_Tests' do
    inherit! :search_paths

  end
end
